_target_: vibravox.lightning_modules.regressive_mimi.RegressiveMimiLightningModule

sample_rate: ${sample_rate}
description: "RegressiveMiMi"

defaults:
  - optimizer: adam
  - loss_module@loss_feature_fn: l1
