noresqa_mos:
  _target_: vibravox.metrics.noresqa_mos.NoresqaMOS
  sample_rate: 16000

torchmetrics_si_sdr:
  _target_: torchmetrics.audio.ScaleInvariantSignalDistortionRatio

torchmetrics_stoi:
  _target_: torchmetrics.audio.ShortTimeObjectiveIntelligibility
  fs: 16000

torchsquim_stoi:
  _target_: vibravox.metrics.torchsquim_stoi.TorchsquimSTOI