_target_: src.data.lightning_datamodule.asr.ASRLightningDataModule
dataset_name: 'cnamLMSSC/vibravox'
dataset_configuration: 'french'
number_of_hours_train: 10min
language: 'fr'
max_input_length_in_sec: -1 #-1 for all audios (no_filter/)
min_input_length_in_sec: 0.0 #0.0 for no minimum duration
sampling_rate: 16000
batch_size: ${batch_size}
num_workers: ${num_workers}
pin_memory: True
processor_class: 'transformers.Wav2Vec2Processor'
processor: '/configs/processor_config/wav2vec2processor'
ckpt_path: ${ckpt}
is_test: ${is_test}
is_continue_training: ${is_continue_training}
task_type: ${task_type}