rich_model_summary:
  _target_: pytorch_lightning.callbacks.RichModelSummary

checkpoint_callback_last:
  _target_: src.callbacks.asr_checkpoint.ASRCheckpoint
  save_last: True
  dirpath: ${hydra:runtime.cwd}/models/
  filename: "${now:%Y-%m-%d}/${now:%H-%M-%S}/last-{epoch}"

checkpoint_callback_top_k:
  _target_: src.callbacks.asr_checkpoint.ASRCheckpoint
  save_top_k: 3
  monitor: "val/per_ctc"
  mode: "min"
  dirpath: ${hydra:runtime.cwd}/models/
  filename: "${now:%Y-%m-%d}/${now:%H-%M-%S}/{epoch}"

early_stopping_callback:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: "val/per_ctc"
  mode: "min"
  patience: 120

lr_logger_callback:
  _target_: pytorch_lightning.callbacks.lr_monitor.LearningRateMonitor
  logging_interval: "step"
