import pickle

from pathlib import Path


# Load the pickle file located in pkfile_path generated by scripts/gen_pairs_for_spkv.py :
pickle_file = f"/home/jhauret/Desktop/github/vibravox/configs/lightning_datamodule/spkv_pairs/vibravox/speech_noisy/mixed_gender.pkl"
pickle_path = Path(__file__).parent.parent.parent / pickle_file

if not pickle_path.exists():
    raise ValueError(
        f"File {pickle_path} does not exist, please generate one for your dataset using scripts/gen_pairs_for_spkv.py")

with open(pickle_path, 'rb') as file:
    pairs = pickle.load(file)

print(f"{len(pairs)=}")